<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>stlx</string>
		<string>setlx</string>
	</array>
	<key>name</key>
	<string>SetlX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#statements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#fucntions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#values</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>afterbacktrack</key>
		<dict>
			<key>begin</key>
			<string>(afterBacktrack)(\s*)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.check.afterbacktrack.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>assigment-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\+\=)</string>
					<key>name</key>
					<string>keyword.operator.assigment.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-\=)</string>
					<key>name</key>
					<string>keyword.operator.assigment.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\*\=)</string>
					<key>name</key>
					<string>keyword.operator.assigment.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(/\=)</string>
					<key>name</key>
					<string>keyword.operator.assigment.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\\\=)</string>
					<key>name</key>
					<string>keyword.operator.assigment.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\%\=)</string>
					<key>name</key>
					<string>keyword.operator.assigment.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\:\=)</string>
					<key>name</key>
					<string>keyword.operator.assigment.direct.setlx</string>
				</dict>
			</array>
		</dict>
		<key>atomic-comment</key>
		<dict>
			<key>comment</key>
			<string>combination of the atomic single-line- and multi-line-comments</string>
			<key>name</key>
			<string>comment.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atomic-comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-comment-block</string>
				</dict>
			</array>
		</dict>
		<key>atomic-comment-block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>atomic value, uninterpreted, multiple-line-comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.setlx</string>
		</dict>
		<key>atomic-comment-line</key>
		<dict>
			<key>comment</key>
			<string>atomic value, uninterpreted, one-line-comment</string>
			<key>match</key>
			<string>(//)(.)*</string>
			<key>name</key>
			<string>comment.line.setlx</string>
		</dict>
		<key>atomic-double</key>
		<dict>
			<key>comment</key>
			<string>atomic value, double</string>
			<key>match</key>
			<string>((0)*(\d)+)?(\.)(\d)+((e|E)(\+|\-)?(\d)+)?</string>
			<key>name</key>
			<string>constant.numeric.double.setlx</string>
		</dict>
		<key>atomic-false</key>
		<dict>
			<key>comment</key>
			<string>atomic value, false</string>
			<key>match</key>
			<string>\b(false)\b</string>
			<key>name</key>
			<string>constant.language.setlx</string>
		</dict>
		<key>atomic-functionSymbol</key>
		<dict>
			<key>comment</key>
			<string>combination of all three ways to defina a functionSymbol for a term</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atomic-functionSymbol-escaped</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-functionSymbol-internal</string>
				</dict>
			</array>
		</dict>
		<key>atomic-functionSymbol-escaped</key>
		<dict>
			<key>comment</key>
			<string>atomic value, functionSymbol for a term, used by the user to define a custom Term</string>
			<key>match</key>
			<string>((@[a-zA-Z])([a-zA-Z0-9]|_)+)</string>
			<key>name</key>
			<string>entity.functionSymbol.escaped.setlx</string>
		</dict>
		<key>atomic-functionSymbol-internal</key>
		<dict>
			<key>comment</key>
			<string>atomic value, functionSymbol for a term, used internally for definitions</string>
			<key>match</key>
			<string>((@@@[a-zA-Z])([a-zA-Z0-9]|_)+)</string>
			<key>name</key>
			<string>entity.functionSymbol.internal.setlx</string>
		</dict>
		<key>atomic-int</key>
		<dict>
			<key>comment</key>
			<string>atomic value, number</string>
			<key>match</key>
			<string>(0)*(\d)+</string>
			<key>name</key>
			<string>constant.numeric.int.setlx</string>
		</dict>
		<key>atomic-languageConstant</key>
		<dict>
			<key>comment</key>
			<string>combination of the three atomic, basic, language-defined constants</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atomic-om</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-true</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-false</string>
				</dict>
			</array>
		</dict>
		<key>atomic-literal</key>
		<dict>
			<key>comment</key>
			<string>atomic value, literal</string>
			<key>match</key>
			<string>(\')(\'\'|(?!\').)*(\')</string>
			<key>name</key>
			<string>string.quoted.setlx</string>
		</dict>
		<key>atomic-number</key>
		<dict>
			<key>comment</key>
			<string>combination of all ways to define a nuber</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atomic-number-fraction</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-int</string>
				</dict>
			</array>
		</dict>
		<key>atomic-number-fraction</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.fraction.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atomic-int</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-double</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(/)(?!\*|/|=)</string>
					<key>name</key>
					<string>constant.numeric.fraction.setlx</string>
				</dict>
			</array>
		</dict>
		<key>atomic-om</key>
		<dict>
			<key>comment</key>
			<string>atomic value, om</string>
			<key>match</key>
			<string>\b(om)\b</string>
			<key>name</key>
			<string>constant.language.setlx</string>
		</dict>
		<key>atomic-string</key>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.setlx</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>atomic value, string</string>
			<key>end</key>
			<string>(\")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.setlx</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?!(\\.)).)</string>
					<key>name</key>
					<string>string.quoted.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\\.)</string>
					<key>name</key>
					<string>constant.character.escape.setlx</string>
				</dict>
			</array>
		</dict>
		<key>atomic-true</key>
		<dict>
			<key>comment</key>
			<string>atomic value, true</string>
			<key>match</key>
			<string>\b(true)\b</string>
			<key>name</key>
			<string>constant.language.setlx</string>
		</dict>
		<key>atomic-variable-name</key>
		<dict>
			<key>match</key>
			<string>(([a-zA-Z])([a-zA-Z0-9]|_)+)</string>
			<key>name</key>
			<string>meta.variable.setlx</string>
		</dict>
		<key>atomics</key>
		<dict>
			<key>comment</key>
			<string>combination of all atomic values</string>
			<key>name</key>
			<string>meta.atomic.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atomic-languageConstant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-functionSymbol</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-variable-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomic-comment</string>
				</dict>
			</array>
		</dict>
		<key>branches</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#else-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#switch</string>
				</dict>
			</array>
		</dict>
		<key>cached-procedure</key>
		<dict>
			<key>begin</key>
			<string>\b(cachedProcedure)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.cachedProcedure.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.cachedProcedure.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>call</key>
		<dict>
			<key>begin</key>
			<string>([a-z]\w*)(\s*\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>meta.call.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>catch</key>
		<dict>
			<key>begin</key>
			<string>\b((catchLng)|(catchUsr)|(catch))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.catch.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\)\s*\{)</string>
					<key>name</key>
					<string>meta.catch.evar.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>check</key>
		<dict>
			<key>begin</key>
			<string>(check)(\s*)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.check.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(backtrack)\b</string>
					<key>name</key>
					<string>meta.check.backtrackcall.setlx keyword.control.setlx</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>check-backtrack</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#check</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#afterbacktrack</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>\b(class)\b(\s+)([a-z]\w*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.setlx</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.class.name.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\;)</string>
			<key>name</key>
			<string>meta.class.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\)\s*\{)</string>
					<key>name</key>
					<string>meta.class.args.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(static)\b(\s*\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.setlx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>name</key>
					<string>meta.class.staticMembers.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>closure</key>
		<dict>
			<key>begin</key>
			<string>\b(closure)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.closure.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.closure.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>collections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list-access</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
			</array>
		</dict>
		<key>comparison-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\=\=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\!\=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;\=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&gt;\=)</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(notin)\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(in)\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.setlx</string>
				</dict>
			</array>
		</dict>
		<key>do-while</key>
		<dict>
			<key>begin</key>
			<string>\b(do)\b(\s*)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\)\;)</string>
			<key>name</key>
			<string>meta.doWhile.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\})(\s*)(while)(\s*)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.setlx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\)\s*\{)</string>
					<key>name</key>
					<string>meta.doWhile.condition.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>else-block</key>
		<dict>
			<key>begin</key>
			<string>\b(else)\b(\s*\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.elseBlock.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>error-handling</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#throw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#try-catch</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#check-backtrack</string>
				</dict>
			</array>
		</dict>
		<key>exists</key>
		<dict>
			<key>match</key>
			<string>\b(exists)\b</string>
			<key>name</key>
			<string>keyword.operator.setlx</string>
		</dict>
		<key>for</key>
		<dict>
			<key>begin</key>
			<string>\b(for)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.for.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\)\s*\{)</string>
					<key>name</key>
					<string>meta.for.iterators.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>forall</key>
		<dict>
			<key>match</key>
			<string>\b(forall)\b</string>
			<key>name</key>
			<string>keyword.operator.setlx</string>
		</dict>
		<key>fucntions</key>
		<dict>
			<key>name</key>
			<string>meta.function.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lambda</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#procedure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cached-procedure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#closure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#call</string>
				</dict>
			</array>
		</dict>
		<key>function-signature</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\)\s*\{)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\:\=)</string>
					<key>name</key>
					<string>keyword.control.defaultParam.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(rw)</string>
					<key>name</key>
					<string>storage.type.modifier.setlx</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>general-collection</key>
		<dict>
			<key>name</key>
			<string>meta.collection.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.collection.ranges.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\:)</string>
							<key>name</key>
							<string>keyword.operator.setlx</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.collection.conditions.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\|)</string>
							<key>name</key>
							<string>keyword.operator.setlx</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>if</key>
		<dict>
			<key>begin</key>
			<string>(\belse\s+)?\b(if)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.if.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\)\s*\{)</string>
					<key>name</key>
					<string>meta.if.condition.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>comment</key>
			<string>combination of all "keyowrds" available</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#assigment-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comparison-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#product-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prefix-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#exists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#forall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#negator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#range-sign</string>
				</dict>
			</array>
		</dict>
		<key>lambda</key>
		<dict>
			<key>name</key>
			<string>meta.lambda.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\|\-\&gt;)</string>
					<key>name</key>
					<string>storage.type.lambda.procedure.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\|\=\&gt;)</string>
					<key>name</key>
					<string>storage.type.lambda.closure.setlx</string>
				</dict>
			</array>
		</dict>
		<key>lin-alg</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#setl-matrix-vector</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.enclosing.list.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.enclosing.list.setlx</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general-collection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>list-access</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9\_\]]+)(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.list.access.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.list.access.setlx</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>logic-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\=\&gt;)</string>
					<key>name</key>
					<string>keyword.operator.logic.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\|\|)</string>
					<key>name</key>
					<string>keyword.operator.logic.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\&amp;\&amp;)</string>
					<key>name</key>
					<string>keyword.operator.logic.setlx</string>
				</dict>
			</array>
		</dict>
		<key>loops</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#while</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#do-while</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((continue)|(break))\b</string>
					<key>name</key>
					<string>meta.abort.setlx keyword.control.setlx</string>
				</dict>
			</array>
		</dict>
		<key>match</key>
		<dict>
			<key>begin</key>
			<string>(match)(\s*\(.*\))\s*(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.match.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(case)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.setlx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\:)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.setlx</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.match.case.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\|)</string>
							<key>name</key>
							<string>keyword.control.setlx</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex-branch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((default)(\s)*(\:))</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>matches</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#match</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scan</string>
				</dict>
			</array>
		</dict>
		<key>negator</key>
		<dict>
			<key>match</key>
			<string>(\!)</string>
			<key>name</key>
			<string>keyword.operator.setlx</string>
		</dict>
		<key>prefix-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\*\*)</string>
					<key>name</key>
					<string>keyword.operator.prefix.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+/)</string>
					<key>name</key>
					<string>keyword.operator.prefix.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\*/)</string>
					<key>name</key>
					<string>keyword.operator.prefix.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\#)</string>
					<key>name</key>
					<string>keyword.operator.prefix.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-)</string>
					<key>name</key>
					<string>keyword.operator.prefix.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+)</string>
					<key>name</key>
					<string>keyword.operator.prefix.setlx</string>
				</dict>
			</array>
		</dict>
		<key>procedure</key>
		<dict>
			<key>begin</key>
			<string>\b(procedure)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.procedure.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.procedure.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function-signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>product-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\*)</string>
					<key>name</key>
					<string>keyword.operator.product.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(/)(?!/|\*)</string>
					<key>name</key>
					<string>keyword.operator.product.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\\)</string>
					<key>name</key>
					<string>keyword.operator.product.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(%)</string>
					<key>name</key>
					<string>keyword.operator.product.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&gt;&lt;)</string>
					<key>name</key>
					<string>keyword.operator.product.setlx</string>
				</dict>
			</array>
		</dict>
		<key>range-sign</key>
		<dict>
			<key>match</key>
			<string>(\.\.)</string>
			<key>name</key>
			<string>keyword.operator.setlx</string>
		</dict>
		<key>regex-branch</key>
		<dict>
			<key>name</key>
			<string>meta.regexBranch.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(regex)\b</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.setlx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.regexp.setlx</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(as)\b</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\|)</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\:\s+)</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</array>
		</dict>
		<key>scan</key>
		<dict>
			<key>begin</key>
			<string>\b(scan)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.scan.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\)\s*)(using)?(\s*\w*\s*)?(\{)</string>
					<key>endCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.setlx</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.scan.expression.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex-branch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(default\s*\:)</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>set</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.enclosing.set.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.enclosing.set.setlx</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general-collection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>setl-matrix-vector</key>
		<dict>
			<key>begin</key>
			<string>(&lt;&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.enclosing.matrix-vector.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&gt;\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.enclosing.matrix-vector.setlx</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#branches</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#matches</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loops</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#error-handling</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(exit)</string>
					<key>name</key>
					<string>meta.abort.setlx keyword.control.setlx</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(return)</string>
					<key>name</key>
					<string>meta.abort.setlx keyword.control.setlx</string>
				</dict>
			</array>
		</dict>
		<key>switch</key>
		<dict>
			<key>begin</key>
			<string>\b(switch)\b(\s*\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.switch.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(case)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.setlx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\:)</string>
					<key>name</key>
					<string>meta.switch.case.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(default\s*\:)\b</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>throw</key>
		<dict>
			<key>match</key>
			<string>\b(throw)\b</string>
			<key>name</key>
			<string>keyword.control.setlx</string>
		</dict>
		<key>try</key>
		<dict>
			<key>begin</key>
			<string>(try)(\s*)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.try.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>try-catch</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#try</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#catch</string>
				</dict>
			</array>
		</dict>
		<key>values</key>
		<dict>
			<key>name</key>
			<string>meta.value.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#collections</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lin-alg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atomics</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\_)</string>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</array>
		</dict>
		<key>while</key>
		<dict>
			<key>begin</key>
			<string>\b(while)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.setlx</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>meta.while.setlx</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\)\s*\{)</string>
					<key>name</key>
					<string>meta.while.condition.setlx</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.setlx</string>
	<key>uuid</key>
	<string>8be6972f-85b1-4d39-b3b5-68bbfdb44d84</string>
</dict>
</plist>
